# CI de Nível 04 - Pipeline Integrada ao Build do Código

# nome da pipeline
name: 'N4 -Execução Integrada'

# gatilhos / triggers - regras de disparo
# gatilho manual = workflow_dispatch

on:
  workflow_dispatch:

  push:
    branches:
      - master

# tarefas dentro da pipeline = jobs
jobs:
  # nome do job
  inspecao:
    #máquina onde o job irá rodar / máquina ubuntu na versão mais recente
    runs-on: ubuntu-latest

    #passos do job
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x

      # instalação do yarn
      - name: Instalando o Yarn
        run: npm install -g yarn

      # instalação das dependências
      - name: Instalando dependências
        run: yarn

      - name: Inspeção de código
        run: yarn lint

  unidade:
    runs-on: ubuntu-latest
    needs: [inspecao]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Executando os testes unitários
        run: yarn test

  e2e-tests:
    runs-on: ubuntu-latest
    needs: [inspecao] # só executa se os jobs de inspe

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Instalando os browsers do playwright
        run: yarn playwright install --with-deps

      - name: Executando os testes e2e
        run: yarn e2e

      - name: Salvando relatórios de testes
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          path: ./playwright-report
          name: Relatório de Testes E2E

  deploy:
    runs-on: ubuntu-latest
    needs: [unidade, e2e-tests] # só executa se os jobs de teste unitário e e2e tiverem sido concluídos com sucesso

    steps:
      - name: Simulação de deploy
        run: echo "Deploy sendo realizado"
